apiVersion: v1
kind: Pod
metadata:
  name: myboot-demo
spec:
  containers:
  - name: myboot-demo
    image: quay.io/rhdevelopers/myboot:v4

    volumeMounts:
      - mountPath: /tmp/demo
        name: demo-volume
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
    - name: demo-volume
      emptyDir: {}